core/urls.py
from django.urls import path
from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
]

formulaAPP/urls.py
from django.contrib import admin
from django.urls import path, include
from formulario.urls import formulario_patterns

urlpatterns = [
    path('', include('core.urls')),
    path('formulario/', include(formulario_patterns)),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

]

formulario/urls.py
from django.urls import path
#from . import views
from .views import  AGGCommentUpdate, DetalleOrdenListView_tesoreria, DetalleOrdenListView_aprobador, enviarView, DetalleOrdenUpdate, DetalleOrdenListView, DetalleOrdenDelete, ClienteListView


formulario_patterns = ([
    path('', DetalleOrdenListView.as_view(), name="View_DetalleOrden"),
    path('create/<int:pk>/', enviarView.as_view(), name="createFormDetalleOrden"),
    path('selectClient', ClienteListView.as_view(), name="selectClientFormDetalleOrden"),
    path('update/<int:pk>/', DetalleOrdenUpdate.as_view(), name="update_DetalleOrden"),
    path('comment/<int:pk>/', AGGCommentUpdate.as_view(), name="update_comentario"), 
    path('delete/<int:pk>/', DetalleOrdenDelete.as_view(), name="Delete_DetalleOrden"),
    path('lista_tesoreria', DetalleOrdenListView_tesoreria.as_view(), name="View_DetalleOrden_tesoreria"),
    path('lista_aprobador', DetalleOrdenListView_aprobador.as_view(), name="View_DetalleOrden_aprobador"),
],'formUrl')

formulario/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import Signal

from django.contrib.auth import get_user_model
TIPOCONTAC_CHOICES = ( 
    (1, "Cliente (Comercial)"), 
    (2, "Bill To (Facturación y Boletas)"), 
    (3, "Ship To (Sólo Envio)"), 
)  

CATECONTACT_CHOICES = ( 
    (1, "EMPRESAS"), 
    (2, "COLEGIOS"), 
    (3, "UNIVERSIDADES"), 
    (4, "FUNCIONARIOS"), 
    (5, "PERSONAS"), 
)

class Cliente (models.Model):
    id_client=models.CharField(max_length=100, verbose_name="Id del cliente",primary_key=True)
    name_cliente= models.CharField(max_length=100, verbose_name="Nombre del Cliente")
    RUT_cliente= models.CharField(max_length=100, verbose_name="RUT del Cliente")
    categoria_cliente= models.IntegerField(default="EMPRESAS",choices=CATECONTACT_CHOICES, verbose_name="Categoria de Cliente")
    name_contact=models.CharField(max_length=100, verbose_name="Nombre contacto")
    tipo_contact=models.IntegerField(default="Cliente (Comercial)",choices=TIPOCONTAC_CHOICES, verbose_name="Tipo de contacto")
    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"
        ordering=['name_cliente']
        
    def __str__(self):
        return self.id_client

DEMO_CHOICES = ( 
    ("Boleta", "Boleta"), 
    ("Factura", "Factura"), 
)  


#derecha se muestra
alimentacion_CHOICES = ( 
    ("SI", "SI"), 
    ("NO", "NO"), 
)  
solicitud_CHOICE = ( 
    ("NUEVA ORDEN", "NUEVA ORDEN"), 
    ("AUMENTO DE ORDEN", "AUMENTO DE ORDEN"), 
    ("MODIFICACION DE ORDEN", "MODIFICACION DE ORDEN"), 
)
estado_orden_CHOICE = ( 
    (1, "Guardado"), 
    (2, "Enviado"), 
    (3, "Aprobado"),
    (4, "Pendiente con observaciones"),
    (5, "Rechazar"),
    (6, "Aprobado tesoreria"),
    (7, "Pendiente con observaciones tesoreria"),
    (8, "Rechazar tesoreria"),
)  

class DetalleOrden(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    client=models.ForeignKey(Cliente, on_delete=models.PROTECT,verbose_name="Cliente")
    solicitud= models.CharField(default='NUEVA ORDEN',choices=solicitud_CHOICE,max_length=100, verbose_name="Tipo de Solicitud")
    aumentoModificacion= models.CharField(max_length=100, verbose_name="En caso de aumento o modificación ingrese el  N° DE ORDEN",blank=True,null=True)
    documentoTributario= models.CharField(max_length=30,choices=DEMO_CHOICES,default='Factura' ,verbose_name="Documento Tributario")
    alimentacion= models.CharField(default='NO',choices=alimentacion_CHOICES,max_length=100, verbose_name="Incluye Alimentación")
    Bandera_enviado=models.IntegerField(choices=estado_orden_CHOICE,default=1,verbose_name="Enviado")
    created = models.DateField(auto_now_add=True)
    sales_program = models.CharField(max_length=100, verbose_name="Sales program")
    coment_ecomer = models.CharField(max_length=5000, verbose_name="Comentarios",blank=True,null=True)
    coment_eteso = models.CharField(max_length=5000, verbose_name="Comentarios",blank=True,null=True)
    num_orden= models.IntegerField(verbose_name="Numero de orden generada",blank=True,null=True)
    class Meta:
        verbose_name = "DetalleOrden"
        verbose_name_plural = "DetalleOrdenes"
        ordering=['client']

class Articulos(models.Model):
    datos=models.ForeignKey(DetalleOrden, on_delete=models.CASCADE,verbose_name="Datos")
    articulo= models.CharField(default=' ',max_length=100, verbose_name="Item",blank=True,null=True)
    cantidad= models.IntegerField(default=0, verbose_name="Cantidad",blank=True,null=True)
    desde = models.DateField(auto_now_add=False, verbose_name="Fecha desde",blank=True,null=True)
    hasta = models.DateField(auto_now_add=False, verbose_name="Fecha hasta",blank=True,null=True)
    valor_bruto = models.IntegerField(verbose_name="Precio bruto",blank=True,null=True)
    detalle= models.CharField(default=' ', max_length=30, verbose_name="Notas",blank=True,null=True)
    class Meta:
        verbose_name = "Articulo"
        verbose_name_plural = "Articulos"
        

formulario/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import DeleteView
from django.views.generic.edit import UpdateView
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from .forms import DetalleOrdenForm_comment, DetalleOrdenForm, ClienteForm, ArticuloForm, DetalleArticuloFormSet, DetalleArticuloFormSet2
#from .forms import Venta_entradas
from .models import DetalleOrden, Cliente, Articulos, User
# Create your views here.

class DetalleOrdenListView(ListView):
    model = DetalleOrden
    
    paginate_by = 8
    def get_queryset(self):
        queryset = super(DetalleOrdenListView, self).get_queryset()
        filter = self.request.GET.get('filter')
        filterId = self.request.GET.get('filterId')
        if filter == 'Guardado':
            queryset = queryset.filter(Bandera_enviado=1)
        elif filter== 'Enviado':
            queryset = queryset.filter(Bandera_enviado=2)
        elif filter== 'Aprobado':
            queryset = queryset.filter(Bandera_enviado=3)
        elif filter== 'Pendiente con observaciones':
            queryset = queryset.filter(Bandera_enviado=4)
        elif filter== 'Rechazar':
            queryset = queryset.filter(Bandera_enviado=5)
        elif filter== 'AprobadoTesoreria':
            queryset = queryset.filter(Bandera_enviado=6)
        elif filter== 'POTesoreria':
            queryset = queryset.filter(Bandera_enviado=7)
        elif filter== 'RechazarTesorería':
            queryset = queryset.filter(Bandera_enviado=8)
        if filterId != '' and filterId!=None:
            queryset = queryset.filter(created=filterId)
            
        return queryset


class DetalleOrdenListView_aprobador(ListView):
    model = DetalleOrden
    template_name = "formulario/detalleorden_list_aprobador.html"
    paginate_by = 5
    def get_queryset(self):
        queryset = super(DetalleOrdenListView_aprobador, self).get_queryset()
        filterId = self.request.GET.get('filterId')
        queryset = queryset.filter(Bandera_enviado=2)
        if filterId != '' and filterId!=None:
            queryset = queryset.filter(created=filterId)
        return queryset

class DetalleOrdenListView_tesoreria(ListView):
    model = DetalleOrden
    template_name = "formulario/detalleorden_list_tesoreria.html"
    paginate_by = 5
    def get_queryset(self):
        queryset = super(DetalleOrdenListView_tesoreria, self).get_queryset()
        filterId = self.request.GET.get('filterId')
        queryset = queryset.filter(Bandera_enviado=3)
        if filterId != '' and filterId!=None:            
            queryset = queryset.filter(created=filterId)

        return queryset


class DetalleOrdenUpdate(UpdateView):
    model=DetalleOrden
    form_class = DetalleOrdenForm
    template_name_suffix = '_update_form'
    success_url=reverse_lazy('formUrl:update_DetalleOrden') 
    def get_success_url(self):
        return reverse_lazy('formUrl:update_DetalleOrden', args=[self.object.id]) + '?ok'


    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        #Obtenemos el comentario si lo tiene
        
        #Obtenemos el formulario
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        #Obtenemos los detalles de la compra
        detalles = Articulos.objects.filter(datos=self.object).order_by('pk')
        detalles_data = []
        for detalle in detalles:
            
            d = {'articulo': detalle.articulo,
                 'cantidad': detalle.cantidad,
                 'desde': detalle.desde,
                 'hasta': detalle.hasta,
                 'valor_bruto': detalle.valor_bruto,
                 'detalle': detalle.detalle}
            detalles_data.append(d)
        #Ponemos como datos iniciales del formset el diccionario que hemos obtenido
        if self.object.Bandera_enviado == 2 or self.object.Bandera_enviado == 3 or self.object.Bandera_enviado == 5 or self.object.Bandera_enviado == 6:
            detalle_compra_form_set = DetalleArticuloFormSet2(initial=detalles_data)
        elif self.object.Bandera_enviado == 1 or self.object.Bandera_enviado == 4:
            detalle_compra_form_set = DetalleArticuloFormSet(initial=detalles_data)

        #Renderizamos el formulario y el formset

        return self.render_to_response(self.get_context_data(form=form,
            detalle_compra_form_set=detalle_compra_form_set,comment=self.object.coment_ecomer))

    def post(self, request, *args, **kwargs):

        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        detalle_form_set = DetalleArticuloFormSet(request.POST)
        
        if form.is_valid() and detalle_form_set.is_valid():
            if 'Actualizar' in request.POST:
                self.object = form.save() 
                detalle_form_set.instance =self.object
                Articulos.objects.filter(datos = self.object).delete()
                detalle_form_set.save()
                #return redirect('formUrl:View_DetalleOrden')
            elif 'Enviar' in request.POST:
                self.object.Bandera_enviado = 2
                self.object.save()
                detalle_form_set.instance =self.object
                Articulos.objects.filter(datos = self.object).delete()
                detalle_form_set.save()
                #return redirect('formUrl:View_DetalleOrden')
            elif 'Aceptar' in request.POST:
                self.object.Bandera_enviado = 3
                self.object.save()
                return redirect('formUrl:View_DetalleOrden_aprobador')
            elif 'Revisar' in request.POST:
                return redirect('formUrl:update_comentario', pk=self.object.id)
            elif 'Rechazar' in request.POST:
                self.object.Bandera_enviado = 5
                self.object.save()
                return redirect('formUrl:View_DetalleOrden_tesoreria')
            elif 'Aceptar_tesoreria' in request.POST:
                self.object.Bandera_enviado = 6
                self.object.save()
                return redirect('formUrl:View_DetalleOrden_tesoreria')
            elif 'Revisar_tesoreria' in request.POST:
                return redirect('formUrl:update_comentario', pk=self.object.id)
            elif 'Rechazar_tesoreria' in request.POST:
                self.object.Bandera_enviado = 8
                self.object.save()
                return redirect('formUrl:View_DetalleOrden_tesoreria')
        
        return super().post(request, *args, **kwargs)


class AGGCommentUpdate(UpdateView):
    model=DetalleOrden
    template_name = "formulario/detalleorden_confirm_comment.html"
    success_url=reverse_lazy('formUrl:update_comentario') 
    def get_success_url(self):
        return reverse_lazy('formUrl:update_comentario', args=[self.object.id]) + '?ok'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        #Obtenemos el formulario
        form = DetalleOrdenForm_comment
        #Renderizamos el formulario y el formset
        return self.render_to_response(self.get_context_data(form=form))

    def post(self, request, *args, **kwargs):

        self.object = self.get_object()
        form=DetalleOrdenForm_comment
        if request.method == "POST":
            form = DetalleOrdenForm_comment(request.POST)                      
            if form.is_valid():
                if 'SiEnviarApro' in request.POST:
                    #sirve mucho para unificar
                    #print(request.user.groups.all().values().get()['name'])


                    self.object.coment_ecomer=request.POST.get('comentario','')
                    self.object.Bandera_enviado = 4
                    self.object.save()
                    #return redirect('formUrl:update_comentario', pk=self.object.id)
                elif 'SiEnviarTeso' in request.POST:
                    self.object.coment_ecomer=request.POST.get('comentario','')
                    self.object.Bandera_enviado = 7
                    self.object.save()
                    #return redirect('formUrl:update_comentario', pk=self.object.id)
        
        return render(request, 'core/home.html')




class DetalleOrdenDelete(DeleteView):
    model=DetalleOrden
    success_url=reverse_lazy('formUrl:View_DetalleOrden')

class ClienteListView(ListView):
    model = Cliente    
    paginate_by = 8
    def get_queryset(self):
        queryset = super(ClienteListView, self).get_queryset()
        filterId = self.request.GET.get('filterId')        
        if filterId != '' and filterId!=None:
            queryset = queryset.filter(id_client=filterId)

        return queryset


class enviarView(TemplateView):
    model = Cliente
    template_name = "formulario/detalleorden_form.html"
    success_url=reverse_lazy('formUrl:View_DetalleOrden')
    #form_class= DetalleOrdenForm

    def get(self, request, *args, **kwargs):              
        self.object=None
        form = DetalleOrdenForm()
        DOrden = DetalleArticuloFormSet()
        return self.render_to_response(self.get_context_data(form=form,
                                                         detalle_compra_form_set=DOrden))

    def post(self, request, *args, **kwargs):    
        form = DetalleOrdenForm(request.POST)
        detalle_form_set = DetalleArticuloFormSet(request.POST)
        context = self.get_context_data(**kwargs)
        client=self.model.objects.get(id_client=context['pk'])
        
        if form.is_valid() and detalle_form_set.is_valid():
            if 'Guardar' in request.POST:                
                post = form.save(commit=False)
                post.client=client
                post.Bandera_enviado=1

formulario/templates/formulario/detalleorden_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Borrar página{% endblock %}
{% block content %}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
            <form action="" method="post">{% csrf_token %}
                <p>¿Estás seguro de que quieres borrar?</p>
                <input type="submit" value="Sí, borrar la página" />
            </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

formulario/templates/formulario/detalleorden_list.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Contacto{% endblock %}
{% include 'formulario/includes/pages_menu.html' %}
{% block content %}

<main role="main">
  <div class="container mb-4">
    <form action="{% url 'formUrl:View_DetalleOrden' %}" method="GET">
      
      <div class="input-group" >
        <div class="input-group date" id="datetimepicker4" data-target-input="nearest" style="width:200px">
          Fecha 
          <input type="data" name="filterId"  class="form-control datetimepicker-input" data-target="#datetimepicker4"/>
          <div class="input-group-append" data-target="#datetimepicker4" data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>              
          </div>
        </div>
        <input type="submit" value="Filtrar">   
      </div>
          
      <script type="text/javascript">
          $(function () {
              $('#datetimepicker4').datetimepicker({
                  format: 'YYYY-MM-D',
                  autoclose: true,
                  locale: 'es'                  
                                    
              });
          });
      </script>
       
        
      {% csrf_token %}
    </form>
    <div>
      
      <a href="{% url 'formUrl:View_DetalleOrden' %}">All</a>|
      <a href="{% url 'formUrl:View_DetalleOrden' %}?filter=Guardado">Guardado</a>|
      <a href="{% url 'formUrl:View_DetalleOrden' %}?filter=Enviado">Enviado</a>|
      <a href="{% url 'formUrl:View_DetalleOrden' %}?filter=Aprobado">Aprobado</a>|
      <a href="{% url 'formUrl:View_DetalleOrden' %}?filter=Pendiente con observaciones">Pendiente con observaciones</a>|
      <a href="{% url 'formUrl:View_DetalleOrden' %}?filter=Rechazar">Rechazado</a>|
      <a href="{% url 'formUrl:View_DetalleOrden' %}?filter=AprobadoTesoreria">Aprobado tesorería</a>|
      <a href="{% url 'formUrl:View_DetalleOrden' %}?filter=POTesoreria">Pendiente con observaciones tesorería</a>|
      <a href="{% url 'formUrl:View_DetalleOrden' %}?filter=RechazarTesorería">Rechazar tesorería</a>|
    </div>
    
    {% if 'ok' in request.GET %}
      <p style="color:green;">
        Página editada correctamente. 
      </p>
    {% endif %}
    <table class="table table-bordered">
      <thead>
        <tr>
          <td>Fecha de creación</td>
          <td>Nombres cliente</td>
          <td>RUT del cliente</td>
          <td>aumentoModificacion</td>
          <td>Documento Tributario</td>
          <td>Incluye Alimentación</td>
          <td>Estado</td>
          <td>Acciones</td>
          
        </tr>
        
      </thead>
      <tbody>
        {% if object_list %}
          {% for DetalleOrden in detalleorden_list %}
            <tr>
              <td>{{ DetalleOrden.created |date:"d/m/Y"  }}</td>
              <td>{{ DetalleOrden.client.name_cliente }}</td>
              <td>{{ DetalleOrden.client.RUT_cliente }}</td>
              <td>{{ DetalleOrden.aumentoModificacion }}</td>
              <td>{{ DetalleOrden.documentoTributario }}</td>
              <td>{{ DetalleOrden.alimentacion }}</td>
              <td>{{ DetalleOrden.get_Bandera_enviado_display }}</td>              
              <td>
                  {% if request.user.groups.all.values.get.name == 'Vendedor_perfil'  %}
                    <div class="btn-group">
                      {% if 2 == DetalleOrden.Bandera_enviado or 3 == DetalleOrden.Bandera_enviado or 5 == DetalleOrden.Bandera_enviado or 6 == DetalleOrden.Bandera_enviado%}
                        <a href="{% url 'formUrl:update_DetalleOrden' DetalleOrden.id %}" title="Ver" type="button" class="btn btn-success">Ver </a>
                      {% endif %}
                      {% if 1 == DetalleOrden.Bandera_enviado or 4 == DetalleOrden.Bandera_enviado %}
                        <!-- Creamos 3 botones que son ver, Editar y Eliminar, nos sirven para gestionar nuestros registros -->
                        <a href="{% url 'formUrl:update_DetalleOrden' DetalleOrden.id %}" title="Ver" type="button" class="btn btn-primary">Ver o editar </a>
                        <a href="{% url 'formUrl:Delete_DetalleOrden' DetalleOrden.id %}" title="Eliminar" type="button" class="btn btn-danger">Eliminar </a>
                      {% endif %}
                    </div>
                  {% endif %}
              </td>
            </tr>
          {% endfor %}
        
        {% else %}
        <h1>No hay registros </h1>
        {% endif %}
      </tbody>
    </table>
              <!-- Menú de paginación -->
      {% if is_paginated %}
        <nav aria-label="Page navigation">
          <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
              <li class="page-item ">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">&laquo;</a>
              </li>
            {% endif %}
            {% for i in paginator.page_range %}
              <li class="page-item {% if page_obj.number == i %}active{% endif %}">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
              </li>
            {% endfor %}
            {% if page_obj.has_next %}
              <li class="page-item ">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">&raquo;</a>
              </li>
            {% endif %}
          </ul>
        </nav>
      {% endif %}
  </div>
</main>
{% endblock %}

formulario/templates/formulario/detalleorden_list_aprobador.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Contacto{% endblock %}
{% include 'formulario/includes/pages_menu.html' %}
{% block content %}

<main role="main">
  <div class="container mb-4">
    <form action="{% url 'formUrl:View_DetalleOrden_aprobador' %}" method="GET">
       ID : 
        <input type="number" name="filterId"  style="width:60px" / >
        <input type="submit" value="Filtrar">
        
        {% csrf_token %}
    </form>
    <table class="table table-bordered">
      <thead>
        <tr>
          <td>Nombres cliente</td>
          <td>Tipo de Solicitud</td>
          <td>aumentoModificacion</td>
          <td>Documento Tributario</td>
          <td>Incluye Alimentación</td>
          <td>Acciones</td>
        </tr>
        
      </thead>
      <tbody>
        {% if object_list %}
        {% for DetalleOrden in detalleorden_list %}
        <tr>
          <td>{{ DetalleOrden.client.name_cliente }}</td>
          <td>{{ DetalleOrden.solicitud }}</td>
          <td>{{ DetalleOrden.aumentoModificacion }}</td>
          <td>{{ DetalleOrden.documentoTributario }}</td>
          <td>{{ DetalleOrden.alimentacion }}</td>
          
          <td>

            {% if request.user.groups.all.values.get.name == 'Aprobador_perfil'  %}
               {% if 2 == DetalleOrden.Bandera_enviado %}
                  <a href="{% url 'formUrl:update_DetalleOrden' DetalleOrden.id %}" title="Ver" type="button" class="btn btn-success">Ver </a>
                {% endif %}
            {% endif %}
          </td>
        </tr>
        {% endfor %}
        
        {% else %}
        <h1>No hay registros</h1>
        {% endif %}
      </tbody>
    </table>

              <!-- Menú de paginación -->
          {% if is_paginated %}
          <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
              {% if page_obj.has_previous %}
                <li class="page-item ">
                  <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">&laquo;</a>
                </li>
              {% endif %}
              {% for i in paginator.page_range %}
                <li class="page-item {% if page_obj.number == i %}active{% endif %}">
                  <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
              {% endfor %}
              {% if page_obj.has_next %}
                <li class="page-item ">
                  <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">&raquo;</a>
                </li>
              {% endif %}
            </ul>
          </nav>
      {% endif %}
  </div>
</main>
{% endblock %}

formulario/templates/formulario/detalleorden_list_tesoreria.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Contacto{% endblock %}
{% include 'formulario/includes/pages_menu.html' %}
{% block content %}

<main role="main">
  <div class="container mb-4">
    <form action="{% url 'formUrl:View_DetalleOrden_aprobador' %}" method="GET">
      <div class="input-group" >
        <div class="input-group date" id="datetimepicker4" data-target-input="nearest" style="width:200px">
          Fecha 
          <input type="data" name="filterId"  class="form-control datetimepicker-input" data-target="#datetimepicker4"/>
          <div class="input-group-append" data-target="#datetimepicker4" data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>              
          </div>
        </div>
        <input type="submit" value="Filtrar">   
      </div>
        
        {% csrf_token %}
    </form>
    <table class="table table-bordered">
      <thead>
        <tr>
          <td>Nombres cliente</td>
          <td>Tipo de Solicitud</td>
          <td>aumentoModificacion</td>
          <td>Documento Tributario</td>
          <td>Incluye Alimentación</td>
          <td>Acciones</td>
        </tr>
        
      </thead>
      <tbody>
        {% if object_list %}
        {% for DetalleOrden in detalleorden_list %}
        <tr>
          <td>{{ DetalleOrden.client.name_cliente }}</td>
          <td>{{ DetalleOrden.solicitud }}</td>
          <td>{{ DetalleOrden.aumentoModificacion }}</td>
          <td>{{ DetalleOrden.documentoTributario }}</td>
          <td>{{ DetalleOrden.alimentacion }}</td>
          
          <td>

            {% if request.user.groups.all.values.get.name == 'Tesoreria_perfil'  %}
               {% if 3 == DetalleOrden.Bandera_enviado %}
                  <a href="{% url 'formUrl:update_DetalleOrden' DetalleOrden.id %}" title="Ver" type="button" class="btn btn-success">Ver </a>
                {% endif %}
            {% endif %}


            <!-- Futuro solo 1 y no 3 
            {% if request.user.groups.all.values.get.name == 'Aprobador_perfil'  %}
               {% if 2 == DetalleOrden.Bandera_enviado %}
                  <a href="{% url 'formUrl:update_DetalleOrden' DetalleOrden.id %}" title="Ver" type="button" class="btn btn-success">Ver </a>
                {% endif %}
            {% endif %}-->


            
          </td>
        </tr>
        {% endfor %}
        
        {% else %}
        <h1>No hay registros</h1>
        {% endif %}
      </tbody>
    </table>

              <!-- Menú de paginación -->
          {% if is_paginated %}
          <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
              {% if page_obj.has_previous %}
                <li class="page-item ">
                  <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">&laquo;</a>
                </li>
              {% endif %}
              {% for i in paginator.page_range %}
                <li class="page-item {% if page_obj.number == i %}active{% endif %}">
                  <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
              {% endfor %}
              {% if page_obj.has_next %}
                <li class="page-item ">
                  <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">&raquo;</a>
                </li>
              {% endif %}
            </ul>
          </nav>
      {% endif %}
  </div>
</main>
{% endblock %}